name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    strategy:
      matrix:
        os: [linux]
        version: [jdk8u, jdk11u, jdk16, jdk]
        vm: [hotspot, openj9]
        image: [adoptopenjdk/centos7_build_image]
        include:
          - os: alpine-linux
            version: jdk16
            vm: hotspot
            image: adoptopenjdk/alpine3_build_image
          - os: alpine-linux
            version: jdk
            vm: hotspot
            image: adoptopenjdk/alpine3_build_image
          - os: linux
            version: jdk11u
            vm: dragonwell
            image: adoptopenjdk/centos7_build_image
    steps:
    - uses: actions/checkout@v2

    - name: Build Linux
      run: ./build-farm/make-adopt-build-farm.sh
      env:
        JAVA_TO_BUILD: ${{ matrix.version }}
        ARCHITECTURE: x64
        VARIANT: ${{ matrix.vm }}
        TARGET_OS: ${{ matrix.os }}
        FILENAME: OpenJDK.tar.gz
        # Don't set the OS as we use both linux and alpine-linux
        PLATFORM_CONFIG_LOCATION: AdoptOpenJDK/openjdk-build/master/build-farm/platform-specific-configurations


    - uses: actions/upload-artifact@v2

      name: Collect and Archive Artifacts
      with:
        name: ${{matrix.version}}-${{matrix.os}}-${{matrix.vm}}
        path: workspace/target/*
